# Generated by Django 5.1.5 on 2025-01-30 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='categories',
            new_name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='No author', max_length=255),
        ),
    ]
